Rescue smtp error
umts/st-pax pull request #238
Opened 2020-08-17 19:49 UTC by BenMelz

Closes #236 

Pretty self explanatory. Warn users if the update email doesn't send.
Turns out raising an exception in a `before_save` block doesn't prevent the save from executing, so what I wrote this morning will work fine.

2020-08-18 14:27 UTC, Anbranin submitted a review, later dismissed
This looks good so far but please write tests for it.

2020-08-18 14:32 UTC, BenMelz commented
I knew someone would say that right after I put the PR up

Tests foil me once again!

2020-08-18 16:11 UTC, BenMelz commented
Good thing you made me write those, turns out `before_save` and `after_save` are indeed transactional and whatever I did in the console to come to the conclusion that they were not was not right. `after_commit` is what we're looking for.

2020-08-18 21:40 UTC, werebus commented on app/controllers/passengers_controller.rb
> +                        'but the passenger was unable to be notified of their status change via email.'
A bit too much [passive voice][srbm] for me. Perhaps, "but we could not notify them of their status change" 

[srbm]: https://youtu.be/v-8_LWq236Y

2020-08-18 21:41 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +          allow(PassengerMailer).to receive(:notify_archived).and_raise Net::SMTPFatalError
I would move this to a `before` block inside `'with a broken mailer'`. It's setup that defines that context.

2020-08-18 21:44 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +          @passenger = create :passenger, :permanent, active_status: 'active'
`@passenger` doesn't need to be an instance variable. if it's only used in this block.

That said, maybe it _should_ be in a `let` block?

2020-08-18 21:46 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +          expect(flash[:warning]).to match(/the passenger was unable to be notified of their status change via email/)
I'm always a little wary of super-log regexes for UI strings. Pare it down a bit to the essence of the warning?

2020-08-18 21:52 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +            passenger: {
You can do `attributes_for :passenger, :permanent` to make Factory Bot build this hash.

2020-08-19 19:03 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +          expect(flash[:warning]).to match(Regexp.union(/could not notify/, /status change/))
`Regexp.union` (more or less) creates an alternation. That is, this is the same as `/could not notify|status change/`, which will match if either phase is present in the string. I suspect you wanted _both_. If so, the easiest way is probably two expectations.

2020-09-23 16:57 UTC, werebus requested changes

2020-09-23 16:57 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +  let!(:admin) { create :user, :admin }
Don't need `!`

2020-09-23 16:57 UTC, werebus commented on spec/controllers/passengers_controller_spec.rb
> +  let!(:passenger) { create :passenger, :permanent }
Don't need `!`

2020-09-25 19:05 UTC, werebus approved these changes

2020-09-29 19:58 UTC, merged