Export CSV button added
umts/st-pax pull request #406
Opened 2024-05-08 19:23 UTC by aarinmehta

closes #404

2024-05-08 19:44 UTC, werebus requested changes
Also, the Travis failure is due to a coverage drop. If you add and commit your `.coverage/last_run.json` that will signal, "yes coverage dropped and we, as an organization, are OK with that." But, probably better to write some tests for the code you added.

2024-05-08 19:44 UTC, werebus commented on app/controllers/passengers_controller.rb
> +      format.csv do
This seems like the right approach — use the selected filter on the index — but the link you added doesn't use this.

2024-05-08 19:44 UTC, werebus commented on app/controllers/passengers_controller.rb
> +  def export_csv
I don't think this route is needed (if my other suggestions are adopted).

2024-05-08 19:44 UTC, werebus commented on app/views/passengers/_filters_and_key.html.haml
> +        = link_to('Export CSV', passengers_path(format: 'csv', status: params[:status]), class: 'btn btn-secondary')
Can I perhaps point you to [this comment](https://github.com/umts/st-pax/issues/404#issuecomment-2023941484) as a hint? A form can have more than one submit button — in this case one for PDF, one for CSV.

2024-05-09 14:37 UTC, werebus requested changes

2024-05-09 14:37 UTC, werebus commented on app/views/passengers/_filters_and_key.html.haml
> +        = f.submit 'Export CSV', formaction: passengers_path(format: :csv), class: 'btn btn-secondary'
We've got the `bootstrap_form_tag` helper here in this app, it takes care of the `btn-` classes unless your're doing something "different".

```suggestion
        = f.submit 'Export CSV', formaction: passengers_path(format: :csv)
```

2024-06-04 18:08 UTC, werebus requested changes

2024-06-04 18:08 UTC, werebus commented on coverage/.last_run.json
> +    "line": 86.43
So, this fixes the Travis failure, but I would prefer not to have a coverage drop.

A simple test or two of `Passenger.to_csv` should actually take care of it?

2024-06-11 20:18 UTC, benmelz requested changes

2024-06-11 20:18 UTC, benmelz commented on app/models/passenger.rb
> +
```suggestion
```
Remember we talked about this:

https://github.com/umts/st-pax/blob/324526a2af2eacb5be376edee8db2621a8d8971a/app/models/passenger.rb#L44-L46

Namely that `needs_longer_rides` is not an attribute on `Passenger`. It's just a method that checks if the passenger has a `MobilityDevice` that has `mobility_device.needs_longer_rides == true`.

As such, we shouldn't be adding anything to the model, you just need to set up your test data correctly - more on that below

2024-06-11 20:18 UTC, benmelz commented on spec/models/passenger_spec.rb
> +        create(:passenger, name: 'Jane Smith', needs_longer_rides: false, permanent: false)
```suggestion
        create(:passenger, name: 'John Doe', permanent: true)
        create(:passenger, name: 'Jane Smith', permanent: false)
```
Not passenger attributes

2024-06-11 20:18 UTC, benmelz commented on spec/models/passenger_spec.rb
> +        create(:passenger, name: 'Jane Smith', needs_longer_rides: false, permanent: false)
```suggestion
        longer_rides_mobility_device = create(:mobility_device, needs_longer_rides: true)
        create(:passenger, name: 'John Doe', mobility_device: longer_rides_mobility_device, permanent: true)
        create(:passenger, name: 'Jane Smith', permanent: false)
```
Make one of the passengers need longer rides, by giving them a mobility device that needs longer rides

2024-06-11 20:18 UTC, benmelz commented on spec/models/passenger_spec.rb
> +          John Doe,false,true
```suggestion
          John Doe,true,true
```

2024-06-18 17:55 UTC, werebus requested changes

2024-06-18 17:55 UTC, werebus commented on coverage/.last_run.json
> +    "line": 15.83
Needs a whole test-suite run.

2024-06-25 16:00 UTC, werebus approved these changes

2024-06-25 16:06 UTC, merged